services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: educode
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3306:3306
    volumes:
      - db_volume:/var/lib/mysql
  db_admin:
    depends_on:
      - db
    image: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - 8081:80
volumes:
  db_volume: